image: python:latest


variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - export FLASK_APP=portfolio
  - export FLASK_ENV=development
  - python --version
  - python -m venv .venv
  - source .venv/bin/activate
  - python -m pip install --upgrade pip

test:
  script:
    - pip install flake8 pytest
    - pip install -e .
    - flask init-db
    - flake8 portfolio
    - pytest
